- vtl_adapter/include/vtl_adapter/vtl_command_converter.hpp
- vtl_adapter/src/vtl_command_converter.cpp
headerファイルのrclcpp::Subscription内ではConstSharedPtrは使わないのが正しいはずなので、動くように修正
> fix build error

- v2i_tester/CMakeLists.txt
- v2i_tester/config/vtl_test.clear.env
- v2i_tester/config/vtl_test.default.env
- v2i_tester/config/vtl_test.id.01.env
- v2i_tester/config/vtl_test.id.02.env
- v2i_tester/config/vtl_test.id.03.env
- v2i_tester/config/vtl_test.id.04.env
- v2i_tester/config/vtl_test.mode.turn_dir.left.01.env
- v2i_tester/config/vtl_test.mode.turn_dir.right.01.env
- v2i_tester/config/vtl_test.mode.turn_dir.straight.01.env
- v2i_tester/config/vtl_test.permit_state.01.env
- v2i_tester/config/vtl_test.permit_state.02.env
- v2i_tester/config/vtl_test.permit_state.03.env
- v2i_tester/config/vtl_test.permit_state.04.env
- v2i_tester/config/vtl_test.permit_state.05.env
- v2i_tester/config/vtl_test.permit_state.06.env
- v2i_tester/config/vtl_test.permit_state.07.env
- v2i_tester/config/vtl_test.response_type.and.01.env
- v2i_tester/config/vtl_test.response_type.and.02.env
- v2i_tester/config/vtl_test.response_type.and.03.env
- v2i_tester/config/vtl_test.response_type.match.01.env
- v2i_tester/config/vtl_test.response_type.match.02.env
- v2i_tester/package.xml
- v2i_tester/scripts/generate_json_body.bash
- v2i_tester/scripts/test_vtl_command.bash
- v2i_tester/scripts/update_vtl_command_msg.bash
v2i_interfaceモジュールとしてのテストツール用パッケージを追加します。
使用方法：
1. cd `ros2 pkg prefix v2i_tester`/lib/v2i_tester/
　実行ファイル群があるディレクトリへ移動します。
2. source vtl_test.clear.env
　テスト用環境変数設定をクリアします。
3. source vtl_test.~~.env (clear, default以外)
　テスト用環境変数設定を追加設定します。
　複数回実行することで複数種類の設備設定を埋め込むことができます。
4. source test_vtl_command.bash
　環境変数設定をもとに/autoware_state_machine/stateと/awapi/tmp/infrastracture_commandsを出力します。
構成：
- vtl_test.~~.env (default, clear以外)
- vtl_test.default.envによる初期値設定を読み込みます。
- ユーザ定義により環境変数を書き換えます。
- update_vtl_command_msg.bashによる環境変数の更新（コマンドの整形）を行います。
- vtl_test.clear.env
- 本テスト関連の環境変数を全てunsetします。
　毎テスト実行前に実行してください。
- test_vtl_command.bash
- ユーザ用の実行ファイルです。
- update_vtl_command_msg.bash
- 内部処理用のbashファイルです。
　infrastructure commandを整形します。
- generate_json_body.bash
- メッセージ成形用の関数を定義しています。これは …
> feat: add v2i_tester

- v2i_interface/launch/v2i_interface.launch.xml
- v2i_interface/scripts/v2i_interface.py
- vtl_adapter/src/vtl_command_converter.cpp
- vtl_adapter/src/vtl_state_converter.cpp
- v2i_interfaceより、adapterに移植した機能をごっそり削ぎ落としました。
- interface部分のメッセージ型を変更しました。
- vtl_test.permit_state.01.envを用いた/awapi/tmp/infrastructure_command出力の模擬の結果v2i_interface_test.launch.xmlで表示されるGUIにて"recv write"が表示されることを確認しました。
- 同envによるinfrastructure_commandsの出力中に同GUIより期待値にあった出力（ID=1, GPIO=0x10, Period=1000msec)を出したときに/system/v2x/virtual_traffic_light_statesへ期待出力（下記）が出ることを確認しました。
```
stamp:
sec: 1677436511
nanosec: 615366502
states:
- stamp:
sec: 1677436511
nanosec: 615366502
type: eva_beacon_system
id: "\x01"
approval: true
is_finalized: true
```
テストバリエーションは少ないですが、vtl_test.permit_state.01.envの条件ではv2i_interface↔vtl_adapterの相互通信が正常動作していることを確認済みです。
The PR author **must** check the checkboxes below when creating the PR.
The PR reviewers **must** check the checkboxes below before approval.
The PR …
> feat: apply adapter to v2i interface

- v2i_command_muxer/CMakeLists.txt
- v2i_command_muxer/config/topic_definition.yaml
- v2i_command_muxer/include/v2i_command_muxer/v2i_command_muxer.hpp
- v2i_command_muxer/launch/v2i_command_muxer.launch.xml
- v2i_command_muxer/package.xml
- v2i_command_muxer/src/v2i_command_muxer.cpp
複数のv2i_interface_msgs/msg/infrastructure_commands型のメッセージを集約し任意の周期で出力するコンポーネントを追加実装しました。
起動方法：
ros2 launch v2i_command_muxer v2i_command_muxer.launch.xml
/cargo_loading/infrastructure_commands 10Hzと /v2i_gate/infrastructure_commands 10Hzの入力を与えたときに、
/v2i/infrastructure_commands にてそれぞれの出力結果を合成した出力が出ていることを確認しました。
詳細は下記のとおりです。
入力コマンド
```
ros2 topic pub /cargo_loading/infrastructure_commands v2i_interface_msgs/msg/InfrastructureCommandArray "{commands: [ {id: 1, state: 1} ]}" -r 10
ros2 topic pub /v2i_gate/infrastructure_commands v2i_interface_msgs/msg/InfrastructureCommandArray "{ commands: [ {id: 2, state: 3} ] }" -r 10
```
（期待値：ID=1, state=1とID=2, state=3の２つの指示が混合された状態で出力されることが期待値）
出力確認コマンド
```
ros2 topic echo /v2i/infrastructure_commands
```
出力結果
```
stamp:
sec: 0
nanosec: 0
commands:
- …
```
> feat: add v2i command muxer

- vtl_adapter/src/eve_vtl_attribute.cpp
16進数の文字列を読み込むとfixed_bitでnulloptが返されてしまう不具合を修正しました。
- std::stoiの基数を自動で判別するオプションを有効化し、16進数入力に対応できるようにしました。
　https://cpprefjp.github.io/reference/string/stoi.html
- stoiの例外処理を補強しました。
- bit値の有効値判別の判断条件が誤っていたためこれを修正しました。
vtl_testerの下記のテストケースで動作確認済み。
- vtl_test.response_type.and.01.env
- vtl_test.response_type.match.01.env 
変更前はノードが死亡していたが、変更後はノードが継続的に正常動作することを確認できています。
> fix: function fixed bit

- vtl_adapter/CMakeLists.txt
- vtl_adapter/launch/vtl_adapter.launch.xml
- vtl_adapter/src/vtl_command_converter.cpp
- vtl_adapter/src/vtl_state_converter.cpp
v2i_interfaceとadapterの間にmuxerを挿入するため、adapterのトピック名を変更します。
一部のコンポーネントを一時的に除外したテストも考えられるため、トピック名はlaunchで書き換える前提とし、
ノード実装としては一般名にしてあります。
vtl_testerのテストサンプル（vtl_test.response_type.and.01.env） + v2i_interface_test.launch.xmlによる設備信号模擬により、
期待した出力結果（approved=trueのvirtual_traffic_light_states出力）が得られることを確認済みです。
The PR author **must** check the checkboxes below when creating the PR.
The PR reviewers **must** check the checkboxes below before approval.
The PR author **must** check the checkboxes below before merging.
After all checkboxes are checked, anyone who has write access can merge the PR.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …
> feat: update adapter topic name and connect muxer

- vtl_adapter/include/vtl_adapter/eve_vtl_interface_converter.hpp
- vtl_adapter/src/eve_vtl_interface_converter.cpp
- vtl_adapter/src/vtl_state_converter.cpp
- custom_tag内にtype設定は存在しないため、command_arrayよりtype取得した結果をattribute内に取り込むように変更しました。
- laneltとしてのID設定を出力すべき関数で実設備IDを誤って出力している不具合を修正しました。
> fix(vtl_adapter): remove type from cutom_tags

- vtl_adapter/src/vtl_command_converter.cpp
地図情報の初期化失敗時にノードが死んでしまう不具合を修正しました。
ID、request_bitほかcustom_tagsの値が不正なときにもノードが死なないことを確認しました。
The PR author **must** check the checkboxes below when creating the PR.
The PR reviewers **must** check the checkboxes below before approval.
The PR author **must** check the checkboxes below before merging.
After all checkboxes are checked, anyone who has write access can merge the PR.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/
> fix(vtl_adapter): add exception handling for initialization failure

- vtl_adapter/CMakeLists.txt
- vtl_adapter/include/vtl_adapter/eve_vtl_attribute.hpp
- vtl_adapter/include/vtl_adapter/self_approval_timer.hpp
- vtl_adapter/include/vtl_adapter/vtl_adapter.hpp
- vtl_adapter/src/eve_vtl_attribute.cpp
- vtl_adapter/src/self_approval_timer.cpp
- vtl_adapter/src/vtl_adapter.cpp
下記の挙動を満足できるように修正します。
- request_type==ALWAYSのcommandが与えられた場合には、該当IDに対して（設備応答がなくても）approve出力を出し続けること
- request_type!=ALWAYSのcommandが与えられた場合には、該当IDに対して設備応答がなければapprove出力を返さないこと
現実装では、設備状態に対してevent駆動で動作するようになっており、自己承認の機構が存在していないため前者を満足できていません。本PRとしては、下記のように自己承認の機構を実現するクラスを定義し、追加実装します。
下記について机上確認が完了しています。
- request_type==ALWAYSのcommandが与えられた場合には、該当IDに対して（設備応答がなくても）approve出力を出し続けること
- 手順：
- terminal_1 (for test target)
```
ros2 launch vtl_adapter vtl_adapter.launch.xml
```
- terminal_2 (for result monitoring)
```
ros2 topic echo /system/v2x/virtual_traffic_light_states
```
- terminal_3 (for command dummy)
```
cd `ros2 pkg prefix v2i_tester`/lib/v2i_tester
source vtl_test.clear.env
source vtl_test.permit_state.01.env
source test_vtl_command.bash
```
- 結果：
- ros2 topic …
> feat: add self approval function

- v2i_interface/scripts/test/v2i_interface_test.py
Description
When "v2i_interface_test.py" execute ,"Unable to complete operation on element with key 0" alert.
Tests performed
When "v2i_interface_test.py" execute, no alert.
> fix: pysimplegui window add finalize and layout

- vtl_adapter/src/vtl_command_converter.cpp
vtl_adapterの制御出力としての `/v2i_gate/infrastructure_commands` よりタイムスタンプの埋め込みが漏れていたため追加します。
修正後について、現在時刻のタイムスタンプの埋め込みが正常にできていることを確認済みです。
```
ros2 topic echo /v2i_gate/infrastructure_commands
---
stamp:
sec: 1678328558
nanosec: 578996054
commands:
- stamp:
sec: 1678328553
nanosec: 678525815
id: 8
state: 14
---
```
> feat(vtl_adapter): add timestamp to output command_array

- vtl_adapter/src/eve_vtl_attribute.cpp
setID成功時にtrueを返さねばならないが、誤ってfalseを返す仕様になっていたため修正した。
https://github.com/eve-autonomy/v2i_interface/pull/32 にてエラーメッセージが出力されないことを確認済みである。
> fix(vtl_adapter): fix return value of set id function

- vtl_adapter/include/vtl_adapter/eve_vtl_interface_converter.hpp
- vtl_adapter/include/vtl_adapter/vtl_command_converter.hpp
- vtl_adapter/include/vtl_adapter/vtl_state_converter.hpp
- vtl_adapter/src/eve_vtl_interface_converter.cpp
- vtl_adapter/src/self_approval_timer.cpp
- vtl_adapter/src/vtl_command_converter.cpp
- vtl_adapter/src/vtl_state_converter.cpp
例外発生時に解析可能となるように、エラーメッセージの出力を追加するために下記を変更した。
- RCLCPP_WARN, INFO, DEBUG出力の追加
- RCLCPP_WARN, INFO, DEBUG出力を利用するために必要なrclcpp::Nodeの定義およびコンストラクタ引数の変更
変更において考慮すべき点として下記を満足する必要がある。
1. 通常使用時に余計なWARN / ERROR出力がないこと
2. 異常時に解析できる出力が出ること
特に異常なcustom_tagsが設定された場合については、WARNで出力するように設定している。
一方で通常の使いかたでも異常時でも通りうる条件についてはDEBUG出力に寄せ、解析時に必要があればDEBUG出力を見られるようにしている。
1. 通常使用時に余計なWARN / ERROR出力がないこと
=>下記の最小出力のみとなることを確認済みである。
```
ros2 launch vtl_adapter vtl_adapter.launch.xml 
[INFO] [launch]: All log files can be found below /home/autoware/.ros/log/2023-03-09-22-32-43-235070-npc2001001-3551345
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [vtl_adapter_node-1]: process started with pid [3551351]
[vtl_adapter_node-1] [INFO 1678368763.457382010] [vtl_adapter] init(): VtlStateConverter: …
```
> feat(vtl_adapter): add error messages

- v2i_interface/launch/v2i_interface.launch.xml
- v2i_interface/scripts/udp_control.py
- v2i_interface/scripts/v2i_interface.py
v2i_interfaceは、UDP接続が途絶した場合に再接続を試みる設計になっておらず、可用性が低下している問題がある。
本PRでは、UDP接続が途絶してしまっても、IPアドレスを再認識できれば再度接続を確立できる機能を追加する。
具体的には下記の対策を実施する。
- launch.xmlにrespawn=trueおよびrespawn_delay=1.0を設定する。これにより、ノード終了から1.0sec後にノードが再起動する。
- send_toメソッドでOS Errorにはまり動かなくなる挙動が見えているため、send_toメソッドにtry catchを設定して、例外時に意図的にノード終了へ誘導する。これにより再起動を誘発させる。
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-26498)
通信途絶後、UDPの再接続ができることを確認しました。
```
#通常接続時
[v2i_interface.py-1] [INFO 1678653743.820247972] [v2i_interface.v2i_interface] send_udp_command(): send udp [{'id': 1, 'request': 1}]
[v2i_interface.py-1] [INFO 1678653743.920380012] [v2i_interface.v2i_interface] send_udp_command(): send udp [{'id': 1, 'request': 1}]
...
#途絶
[v2i_interface.py-1] [ERROR 1678653744.020359240] [v2i_interface.v2i_interface] …
```
> feat(v2i_interface): respawn from udp disconnection

- vtl_adapter/src/self_approval_timer.cpp
vtl_adapterでは、response_type=ANDまたはMATCHの条件で平常時でも下記のようにWarningが出力される（しかも出力され続ける）挙動が確認されている。
この挙動は解析時に有用なWarning情報を埋もれさせることが想定されるため、除去する必要がある。
このPRでは、当該Warningを平常時に表示させないように変更する。
```
[INFO] [launch]: All log files can be found below /home/autoware/.ros/log/2023-03-13-13-57-56-093343-npc2001001-476787
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [vtl_adapter_node-1]: process started with pid [476789]
[vtl_adapter_node-1] [INFO 1678683476.317590591] [vtl_adapter] init(): VtlStateConverter: initialized.
[vtl_adapter_node-1] [INFO 1678683476.318587455] [vtl_adapter] init(): VtlCommandConverter: initialized.
[vtl_adapter_node-1] [INFO 1678683476.318793036] [vtl_adapter] init(): SelfApprovalTimer: initialized.
[vtl_adapter_node-1] [INFO 1678683476.318815180] [vtl_adapter] …
```
> fix(vtl_adapter): remove unnecessary warning

- v2i_command_muxer/launch/v2i_command_muxer.launch.xml
v2i_command_muxerは状態を持たず、複数入力を一つにして出力し続けるだけの単純な構造です。
よって、可用性を向上させるのであればrespawnできるようにすることが望ましいです。
本PRでは、同ノードをrespawnできるように変更します。
プロセスkillしても再起動することを確認済みです。
```
ros2 launch v2i_command_muxer v2i_command_muxer.launch.xml 
[INFO] [launch]: All log files can be found below /home/autoware/.ros/log/2023-03-13-14-40-20-995937-npc2001001-495740
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [v2i_command_muxer_node-1]: process started with pid [495804]
[ERROR] [v2i_command_muxer_node-1]: process has died [pid 495804, exit code -15, cmd '/home/autoware/pilot-auto/install/v2i_command_muxer/lib/v2i_command_muxer/v2i_command_muxer_node --ros-args -r __node:=v2i_command_muxer --params-file /home/autoware/pilot-auto/install/v2i_command_muxer/share/v2i_command_muxer/config/topic_definitio …
```
> feat(v2i_command_muxer): add respawn function

- vtl_adapter/include/vtl_adapter/interface_converter_data_pipeline.hpp
- vtl_adapter/src/interface_converter_data_pipeline.cpp
- vtl_adapter/src/self_approval_timer.cpp
vtl_adapterより出力される設備状態がチャタリングしてしまう（これにより車両が停止線から発車できない）問題が発覚した。
下記の条件をみたすと発現する。
- 重複するIDのVirtual traffic lightが定義されていること
- かつ一方はresponse_type = ALWAYSであること
- かつ他方はresponse_type = MATCH または ANDであること
- かつ各々のexpect_bitが異なること
この条件をみたすことで、self approval timerが同一IDの異なるexpect_bitに対する状態を常時出力してしまうため、他方のexpect_bitとのAND/MATCHが成立しなくなってしまう。
本PRではこの問題の修正と、修正に関わるログ出力の変更を実施する。
- 上記のチャタリングが起きていた地図の各々のVTLに対して以下を確認済みである。
- 車両挙動として設備への指示が正しく出ること、設備からの応答によりVTLを通過できること
- Autowareへ伝える設備状態がチャタリングしないこと
(before)
```
stamp:
sec: 1679996717
nanosec: 683385857
states:
- stamp:
sec: 1679996717
nanosec: 683385857
type: eva_beacon_system
id: '607'
approval: true
is_finalized: true
- stamp:
sec: 1679996717
nanosec: 683385857
type: eva_beacon_system
id: '594'
approval: false　　　　　　　　　←ここがチャタリングしている
is_finalized: true
--- …
```
> feat(vtl_adapter): converter_data timeout

- vtl_adapter/src/vtl_command_converter.cpp
- Feature
When the end line is passed (=FINALIZED), stop the command output and ignore the command input.
- Once the VTL state is FINALIZED, stop udp command.
- Once the VTL state is REQUESTING or PASSING, execute udp command.
*Confirmed the same execution result as [v1.0.2](https://github.com/eve-autonomy/v2i_interface/tree/1.0.2)
**PR Author should check the checkboxes below when creating the PR.**
The PR reviewers **must** check the checkboxes below before approval.
The PR author **must** check the checkboxes below before merging.
After all checkboxes are checked, anyone who has write access can merge the PR.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: …
> feat(vtl_adapter) : ignore command after passing the end line

- vtl_adapter/include/vtl_adapter/vtl_adapter.hpp
- vtl_adapter/include/vtl_adapter/vtl_command_converter.hpp
- vtl_adapter/include/vtl_adapter/vtl_state_converter.hpp
- vtl_adapter/src/vtl_adapter.cpp
- vtl_adapter/src/vtl_command_converter.cpp
- vtl_adapter/src/vtl_state_converter.cpp
- Feature
After passing the end line (=FINALIZED), a blank Array is sent.
- In VtlStateConverter class, add callback for VTL commands topic.
- The actions for the callback.
- Once the VTL state is FINALIZED, send blank array.
- Once the VTL state is not FINALIZED, infrastructure states convert v2x states and send.
- The VtlStateConverter and VtlCommandConverter classes use the same subscriber.
To reduce topic traffic, a single subscriber is spread across two classes.
- In VtlAdapterNode class, add callback for VTL commands topic.
- Call the processing of classes that is executed when a VTL command topic is received.
- VtlStateConverter class.
- VtlCommandConverter class.
In [v1.0.2](https://github.com/eve-autonomy/v2i_interface/tree/1.0.2), Send an blank infrastructure state to reset the …
> feat(vtl_adapter) : send blank array after passing the end line

- v2i_interface/scripts/v2i_interface.py
In the current system, a large amount of UDP transmission logs in v2i is output, 
making it difficult to read the logs and reducing analysis efficiency.
In order to solve this problem, this PR disables the log that is output when sending UDP.
In the current system, when UDP transmission is successful, there is a mechanism to record the UDP transmission success in syslog.
(Analysis is done using syslog only.)
By checking this syslog, the analyst can understand the following.
- If the transmission log remains, at that point, you can see that the process from v2i control input to UDP transmission processing has been consistently successful.
- If the transmission log is interrupted at some point, we know that the UDP transmission has stopped due to some problem in the v2i component.
As a …
> feat(v2i_interface): disable log output send_udp

- v2i_interface/scripts/v2i_interface.py
This PR is revert https://github.com/eve-autonomy/v2i_interface/pull/43.
This is done to address [step 1 of issue-45](https://github.com/eve-autonomy/v2i_interface/issues/45#issue-1813034465).
[Only one PR is targeted](https://github.com/eve-autonomy/v2i_interface/compare/1.1.6...1.1.7), so Step.1 of issue-45 is completed with this PR.
Since it is revertPR and it just returns to the existing behavior, there is no need to check the operation.
Merge https://github.com/eve-autonomy/v2i_interface/pull/43 again in step.4 of [issue-45](https://github.com/eve-autonomy/v2i_interface/issues/45#issue-1813034465).
> revert : "chore(v2i_interface) : send udp log output disable (#43)"

- v2i_interface/scripts/v2i_interface.py
There was an issue where the module crashed when UDP communication failed.
This PR is to fix this error.
By bringing down the network port of Autoware ECU, communication will be interrupted.
As a result, the `v2i_interface` module crashes.
```
[v2i_interface.py-50] [ERROR] [1706062164.976556103] [v2i_interface.v2i_interface]: send udp error
[v2i_interface.py-50] Traceback (most recent call last):
[v2i_interface.py-50]   File "/home/autoware/workspace/autoware_x1/pilot-auto.x1.eve/install/v2i_interface/lib/v2i_interface/v2i_interface.py", line 193, in <module>
[v2i_interface.py-50]     main()
[v2i_interface.py-50]   File "/home/autoware/workspace/autoware_x1/pilot-auto.x1.eve/install/v2i_interface/lib/v2i_interface/v2i_interface.py", line 189, in main
[v2i_interface.py-50]     node.fin() …
```
> feat(v2i_interface) : fixed crash when upd communication failed.

- v2i_interface/CMakeLists.txt
- v2i_interface/README.md
- v2i_interface/launch/v2i_interface_test.launch.xml
- v2i_interface/scripts/test/v2i_interface_test.py
#52 でライセンスの都合から、v2i_interfaceのテストツールを削除した。
削除したことによって、停留所設備連携、設備連携VTL機能の設備を含めた挙動確認ができなくなったため、代替となるテストツールを
tkeasyGUIを使って作成する。
合わせて、インストール方法や立ち上げ方のreadme.mdを追加する。
https://tier4.atlassian.net/browse/AEAP-1018
今回新たに利用するtkeasyGUIは[MITライセンス](https://github.com/kujirahand/tkeasygui-python/blob/main/LICENSE)であることが[README](https://github.com/kujirahand/tkeasygui-python/blob/main/README.md)に明記されている。
> This project adopts the lenient MIT license. This license will not change in the future. Let's enjoy creating GUI programs.
よって#52 にて発生していた課金による問題が現時点ないことからtkeasyGUI採用の懸念はないと判断している。
テストツールの機能確認として、
- v2i_interfaceからUDP通信で送信された情報を受信が正常に動作すること
- 設備を模擬した送信が正常に動作すること
を確認した。
具体的には、v2i_interfaceにUDP通信で車両BXPを模擬した情報を送信して、設備連携機能の評価項目を実施した。
- 停留所設備連携
- 設備連携VTL
が設定されている環境でPlanning_simulatorを実施し、 …
> feat(v2i_interface): add test tool by tkeasygui

- v2i_interface/README.md
v2i_interfaceのテストツールが追加されたが、
installコマンドでエラーが発生してインストールができなかったため、readmeを正しいコマンドに修正する
https://tier4.atlassian.net/browse/AEAP-1018
`pip3 install  TkEasyGUI`
修正後のコマンドでインストールされていることを確認済み。
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: TkEasyGUI in ./.local/lib/python3.10/site-packages (0.2.73)
Requirement already satisfied: pyperclip in ./.local/lib/python3.10/site-packages (from TkEasyGUI) (1.9.0)
Requirement already satisfied: Pillow in ./.local/lib/python3.10/site-packages (from TkEasyGUI) (10.2.0)
```
> fix: update readme.md

- v2i_interface/README.md
readmeを追加された状態でtkeasyguiのv2i_interfaceのテストツールを使用したが、Psimとのローカル通信ができなかったため、readmeを正しいのに修正する。
[internal link](https://tier4.atlassian.net/browse/AEAP-1018)
`ros2 launch v2i_interface v2i_interface_test.launch.xml operation_mode:=local_test`
修正後のコマンドを実行して、設備連携の地図の通信が確立されることを確認済み。
詳細はチケットを参照。
> chore: update readme

- .github/workflows/pre-commit.yaml
https://github.com/eve-autonomy/v2i_interface/pull/59 のPRで導入されたpre-commitは、PRの送信元がフォーク先のブランチであった場合チェックアウトに失敗してしまうので、PRの送信元ブランチをチェックアウトするように変更する
https://github.com/eve-autonomy/v2i_interface/pull/60/checks
でPRの送信元がフォーク先のブランチであっても正しくチェックアウトできていることを確認。
https://github.com/eve-autonomy/v2i_interface/pull/60/checks
でflake8が期待する動作を行っていることを確認。
> ci: modify pre-commit setting
